# Print value with index numbers
print("Hello Mehtab Ali");
name = "Mehtab Ali";
print(name[0]);
print(name[1]);
print(name[2]);
print(name[3]);
print(name[4]);
print(name[5]);
print(name[6]);
print(name[7]);
print(name[8]);
print(name[9]);
# print(name[10]);           (error)

# Loop
print("use in loop")
for char in name:
    print(char)
    

fruitss = "cherry!!!!!!";
print(len(fruitss));            # for length...
print(fruitss[-6:-1]);          # slicing...
print(fruitss.rstrip("!"));     # for erase ! in the variable...
print(fruitss.replace("cherry","Banana"));    # for replace the value cherry to banana...


vari = "hello, Ali HoW Are you Ali";
print(vari.upper());            # Uppercase...
print(vari.lower());            # Lowercase...
print(vari.capitalize());       # Capitilize...
print(vari.split(" "));         # for making list...
print(vari.center(30));         # for center...
print(vari.count("Ali"));       # count how many times appears Ali in this line...

myVari = "hello, Ali HoW Are you Ali";
print(vari.endswith("Ali"));    # Is this value end with Ali...
print(myVari.endswith("HoW",5,14));     # also check the value in between the string by providing start to end index position...
print(myVari.find("HoW Are"));
print(myVari.find("how are"));          # output : (-1) because this value is wrong...
# print(myVari.index("how are"));         # (Error)  it's not give us -1 for false value its return error

varii = "WellComeDear"
print(varii.isalnum());                 # return true because A_Z a-z 0-9. if any other character or punctuation are present it return false...
print(varii.isalpha());                 # (A-Z a-z) return true. if anyother character or punctuation or number are present it return false...
varii = "WellcomeDear";
print(varii.isalpha());
print(varii.islower());                 # if all characters are lowercase then return  true... 
print(varii.isprintable());             # if all characters are printable then return true otherwese for example if any charachter like (\n , \t) are not printable then return false...
print(varii.isspace());                 # if white spaces are present in value then return true if not then return false...
print(varii.istitle());
print(varii.startswith("Well"));        # if your value start with then true else false...
print(varii.swapcase());                # convert upperCase to lowercase and lowercase to upercase...
print(varii.title());                   # all the first character will be tuned in uppercase...




 